name: tf
channels:
  - defaults
dependencies:
  - pip=22.3.1
  - numpy=1.26.4
  - pip:
    - pillow==9.4.0
    - streamlit==1.17.0
    - scikit-learn==1.2.1
    - altair==4.0
    - textblob
    - wordcloud
    - seaborn
    - cufflinks
    - plotly
    - vaderSentiment
    - Scrapy
    
