name: tf
channels:
  - defaults
dependencies:
  - pip=22.3.1
  - pip:
    - numpy
    - pillow
    - streamlit
    - scikit-learn
    - altair
    - textblob
    - wordcloud
    - seaborn
    - cufflinks
    - plotly
    - vaderSentiment
    - Scrapy
    
